services:
  rev-proxy:
    build:
      context: ./system/rev-proxy
    container_name: identity-reverse-proxy
    ports:
      - "9000:80"
    depends_on:
      - api
      - rabbitmq
    restart: unless-stopped

  api:
    build:
      context: ./system/api
    container_name: identity-api
    working_dir: /root/app
    environment:
      - DB_CONNECTION_STRING=sqlite/DigitalIdentity.db
      - ENV_TYPE=dev
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: unless-stopped
    volumes:
      - ./system/api/sqlite:/root/app/sqlite

  blockchain-client:
    build:
      context: ./system/blockchain-client
    container_name: identity-blockchain-client
    depends_on:
      - api
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    build:
      context: ./system/rabbitmq
    container_name: identity-rabbitmq
    volumes:
      - ./system/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
