services:
  rev-proxy:
    build:
      context: ./rev-proxy
    container_name: identity-reverse-proxy
    ports:
      - "9000:80"
    depends_on:
      - api
      - rabbitmq
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: identity-api
    working_dir: /root/app
    environment:
      - DB_CONNECTION_STRING=DigitalIdentity.db
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: unless-stopped

  blockchain-client:
    build:
      context: ./blockchain-client
    container_name: identity-blockchain-client
    depends_on:
      - api
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: identity-rabbitmq
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
