basePath: /bc/v1
host: localhost:9000
info:
  contact: {}
  description: API to verify zkSNARK proofs on Solana blockchain
  title: Digital Identity System - Blockchain Client
  version: "1.0"
paths:
  /verify:
    get:
      consumes:
      - application/json
      description: Retrieves transaction and account data from Solana, extracts zkSNARK
        proof and verifies it
      parameters:
      - description: Transaction signature
        in: query
        name: signature
        required: true
        type: string
      - description: Account public key
        in: query
        name: account
        required: true
        type: string
      - description: Proof size in bytes
        in: query
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully verified proof
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'Invalid request: missing parameters'
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Transaction or account not found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Could not parse input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error or verification failed
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verify zkSNARK proof from Solana account
      tags:
      - zkSNARK
swagger: "2.0"
